### PR TITLE
Allocate arrays on the heap instead of stack.

### PR DESCRIPTION
**Pull request by cetex**
tried up to 16M neurons and it works without crashing.

### CODE REVIEW

**Comment by cetex** [comment]
This was fun! :)

I'm not a c++ wiz in any way, but this was an interesting issue to figure out.
Found that there wasn't a hard limit for the number of neurons, the higher you got the higher the chance increased of it crashing, although sometimes it worked, other times it didn't. If it would be a bug in the code-logic or similar it should've been reproducible every time after a certain number of neurons.
After a while fiddling around and learning how to debug and stuff i found a reference to stack limit and tried ulimit -s 16535 (instead of default 8192) which worked well, so that pointed me towards memory allocation issues.

**Comment by ddigiorg** [comment]
Thank you very much!  I'm not a seasoned C++ expert either, so I had no clue how to approach this issue.  Looks like I need to learn about heaps and stacks.

**Review by Thanh-Binh — COMMENTED** [review]
Hi, I do not think the use of new() is good. In my Ubuntu 16.04 it crashes, sothat I have to turn back into the original version with using array !

**Comment by cetex** [comment]
Hm, that's weird. As far as i see this should be fine although i'm not an expert.. :)

When exactly does it crash?, first render of the ball as usual or even earlier?

**Comment by Thanh-Binh** [comment]
It is segmentation fault. I think delete() causes problems

**Comment by Thanh-Binh** [comment]
Your solution did not work at my laptop
[compute] OpenCL platform: NVIDIA CUDA
[compute] OpenCL device: Quadro M2000M
It crashed by first call encode() at
https://github.com/ddigiorg/simple-cortex/blob/master/source/cortex/area.cpp#L58

with an error like Segmentation fault

**Comment by Thanh-Binh** [comment]
The following dynamical-allocation using std::vector works correctly by me even with 16M neurons.
```C
#include <algorithm>

void Area::encode(ComputeSystem &cs, std::vector<Stimuli> vecStimuli, std::vector<Forest> vecForest)
{
	// Overlap Synapses
	clearNOverlaps(cs);

	for (unsigned int f = 0; f < vecForest.size(); f++)
		overlapSynapses(cs, vecStimuli[f], vecForest[f]);

	// Activate (and potentially Inhibit) Neurons
	clearNStates(cs);
	clearNInhibit(cs);

	_nThresh = static_cast<cl_uint>(vecForest.size());

	activateNeurons(cs);

	cs.getQueue().enqueueReadBuffer(_bufferInhibit, CL_TRUE, 0, _numbytesInhibit, &_inhibit, NULL);

	// If no Neuron Inhibition, activate Neuron with highest Boost value
	if (_inhibit == 0)
	{
		std::vector<cl_uint > arrNBoosts(_numNpA);
		std::vector<cl_uchar> arrNStates(_numNpA);

		cs.getQueue().enqueueReadBuffer(_bufferNBoosts, CL_TRUE, 0, _numbytesNBoosts, arrNBoosts.data(), NULL);
		cs.getQueue().enqueueReadBuffer(_bufferNStates, CL_TRUE, 0, _numbytesNStates, arrNStates.data(), NULL);

		for (unsigned int an = 0; an < _numAN; an++)
		{
			// Get max index
			auto res     = std::max_element(arrNBoosts.begin(), arrNBoosts.end());
			int maxIndex = std::distance(arrNBoosts.begin(), res);

			arrNBoosts[maxIndex] = 0;
			arrNStates[maxIndex] = 1;
		}
		cs.getQueue().enqueueWriteBuffer(_bufferNBoosts, CL_TRUE, 0, _numbytesNBoosts, arrNBoosts.data());
		cs.getQueue().enqueueWriteBuffer(_bufferNStates, CL_TRUE, 0, _numbytesNStates, arrNStates.data());
	}
}

```
It says me that you want to get the last

**Comment by cetex** [comment]
Alright. that looks more like c++ as well :)

**Comment by cetex** [comment]
Closing #6 as this looks better.

**Pull request merged**
